/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "raincounter.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DataPacket, DataPacket, AUTO)


PB_BIND(EventPacket, EventPacket, AUTO)





